//! Encode and decode NGAP PDUs **without macros** — using the raw auto-generated types.
//!
//! This example shows how to work with the APER codec directly:
//! - Constructing an `NGAP_PDU` by hand (ProtocolIE_ID, Criticality, EntryValue, ...)
//! - Encoding to APER wire bytes
//! - Decoding from APER wire bytes
//! - Pattern-matching on decoded IEs
//! - Verifying encode -> decode round-trip fidelity
//!
//! For the same operations using the ergonomic `build_ngap!` / `extract_ngap_ies!`
//! macros, see `build_pdu.rs` and `extract_ies.rs`.

use asn1_codecs::PerCodecData;
use asn1_codecs::aper::AperCodec;
use bitvec::prelude::*;
use oxirush_ngap::ngap::*;

fn main() {
    // ── 1. Build an NGSetupResponse by hand ─────────────────────────────────
    //
    // Every IE must specify its numeric ID, criticality, and typed EntryValue
    // variant. This is what the build_ngap! macro automates.

    // AMF Region ID = 1 (8 bits), AMF Set ID = 1 (10 bits), AMF Pointer = 0 (6 bits)
    let mut region_bv = BitVec::<u8, Msb0>::from_slice(&[0x01]);
    region_bv.truncate(8);
    let mut set_bv = BitVec::<u8, Msb0>::from_slice(&[0x00, 0x40]);
    set_bv.truncate(10);
    let mut ptr_bv = BitVec::<u8, Msb0>::from_slice(&[0x00]);
    ptr_bv.truncate(6);

    let guami = GUAMI {
        plmn_identity: PLMNIdentity(vec![0x02, 0xF8, 0x39]), // MCC=208, MNC=93
        amf_region_id: AMFRegionID(region_bv),
        amf_set_id: AMFSetID(set_bv),
        amf_pointer: AMFPointer(ptr_bv),
        ie_extensions: None,
    };

    // Each IE is a ProtocolIEs_Entry with:
    //   - id: the numeric IE ID (e.g. ID_AMF_NAME = 1)
    //   - criticality: REJECT, IGNORE, or NOTIFY
    //   - value: the typed EntryValue variant (e.g. Id_AMFName(...))
    let ies = vec![
        NGSetupResponseProtocolIEs_Entry {
            id: ProtocolIE_ID(ID_AMF_NAME),
            criticality: Criticality(Criticality::REJECT),
            value: NGSetupResponseProtocolIEs_EntryValue::Id_AMFName(AMFName(
                "OxiRushAMF".to_string(),
            )),
        },
        NGSetupResponseProtocolIEs_Entry {
            id: ProtocolIE_ID(ID_SERVED_GUAMI_LIST),
            criticality: Criticality(Criticality::REJECT),
            value: NGSetupResponseProtocolIEs_EntryValue::Id_ServedGUAMIList(ServedGUAMIList(
                vec![ServedGUAMIItem {
                    guami,
                    backup_amf_name: None,
                    ie_extensions: None,
                }],
            )),
        },
        NGSetupResponseProtocolIEs_Entry {
            id: ProtocolIE_ID(ID_RELATIVE_AMF_CAPACITY),
            criticality: Criticality(Criticality::IGNORE),
            value: NGSetupResponseProtocolIEs_EntryValue::Id_RelativeAMFCapacity(
                RelativeAMFCapacity(255),
            ),
        },
        NGSetupResponseProtocolIEs_Entry {
            id: ProtocolIE_ID(ID_PLMN_SUPPORT_LIST),
            criticality: Criticality(Criticality::REJECT),
            value: NGSetupResponseProtocolIEs_EntryValue::Id_PLMNSupportList(PLMNSupportList(
                vec![PLMNSupportItem {
                    plmn_identity: PLMNIdentity(vec![0x02, 0xF8, 0x39]),
                    slice_support_list: SliceSupportList(vec![SliceSupportItem {
                        s_nssai: S_NSSAI {
                            sst: SST(vec![1]),
                            sd: Some(SD(vec![0x00, 0x00, 0x01])),
                            ie_extensions: None,
                        },
                        ie_extensions: None,
                    }]),
                    ie_extensions: None,
                }],
            )),
        },
    ];

    // The outer PDU wraps the message in a direction + procedure code.
    let pdu = NGAP_PDU::SuccessfulOutcome(SuccessfulOutcome {
        procedure_code: ProcedureCode(ID_NG_SETUP),
        criticality: Criticality(Criticality::REJECT),
        value: SuccessfulOutcomeValue::Id_NGSetup(NGSetupResponse {
            protocol_i_es: NGSetupResponseProtocolIEs(ies),
        }),
    });

    // ── 2. Encode to APER ───────────────────────────────────────────────────
    // Note: the ergonomic way is `pdu.encode()` — here we show the raw codec API.

    let mut output = PerCodecData::new_aper();
    pdu.aper_encode(&mut output).expect("APER encode failed");
    let aper_bytes = output.into_bytes();
    println!("Encoded NGSetupResponse: {} bytes", aper_bytes.len());
    println!("APER hex: {}", hex::encode(&aper_bytes));

    // ── 3. Decode from APER ─────────────────────────────────────────────────
    // Note: the ergonomic way is `NGAP_PDU::decode(&bytes)` — here we show the raw API.

    let mut codec_data = PerCodecData::from_slice_aper(&aper_bytes);
    let decoded = NGAP_PDU::aper_decode(&mut codec_data).expect("APER decode failed");

    // Display impl and inspection helpers (generated by build script)
    println!("\n=== Decoded: {decoded} ===");
    println!(
        "Procedure: {}, Direction: {}\n",
        decoded.procedure_name(),
        decoded.direction()
    );

    // ── 4. Inspect decoded PDU by pattern-matching ──────────────────────────
    //
    // Without macros, you match on the direction, then the procedure variant,
    // then iterate over protocol_i_es and match each EntryValue variant.
    // This is what the extract_ngap_ies! macro automates.

    match &decoded {
        NGAP_PDU::SuccessfulOutcome(outcome) => {
            println!("Type:           SuccessfulOutcome");
            println!("Procedure code: {}", outcome.procedure_code.0);
            println!("Criticality:    {:?}", outcome.criticality.0);

            if let SuccessfulOutcomeValue::Id_NGSetup(ref resp) = outcome.value {
                for ie in &resp.protocol_i_es.0 {
                    match &ie.value {
                        NGSetupResponseProtocolIEs_EntryValue::Id_AMFName(name) => {
                            println!("AMF Name:       {}", name.0);
                        }
                        NGSetupResponseProtocolIEs_EntryValue::Id_RelativeAMFCapacity(cap) => {
                            println!("AMF Capacity:   {}", cap.0);
                        }
                        NGSetupResponseProtocolIEs_EntryValue::Id_ServedGUAMIList(list) => {
                            println!("Served GUAMIs:  {} entries", list.0.len());
                            for guami_item in &list.0 {
                                let plmn = &guami_item.guami.plmn_identity.0;
                                println!(
                                    "  PLMN: {}",
                                    plmn.iter().map(|b| format!("{b:02x}")).collect::<String>()
                                );
                            }
                        }
                        NGSetupResponseProtocolIEs_EntryValue::Id_PLMNSupportList(list) => {
                            println!("PLMN Support:   {} entries", list.0.len());
                            for item in &list.0 {
                                let plmn = &item.plmn_identity.0;
                                println!(
                                    "  PLMN: {}, slices: {}",
                                    plmn.iter().map(|b| format!("{b:02x}")).collect::<String>(),
                                    item.slice_support_list.0.len()
                                );
                            }
                        }
                        _ => {
                            println!("  (other IE: id={})", ie.id.0);
                        }
                    }
                }
            }
        }
        _ => println!("Unexpected PDU type"),
    }

    // ── 5. Verify round-trip ────────────────────────────────────────────────

    let re_encoded = decoded.encode().expect("re-encode failed");
    assert_eq!(aper_bytes, re_encoded, "Round-trip mismatch!");
    println!("\nRound-trip OK ({} bytes)", re_encoded.len());
}
