// Auto-generated by build/registry.rs from ASN.1; do not edit.
use crate::macros::{ies, procedures};
procedures! {
    0 AMFConfigurationUpdate { InitiatingMessage Initiating_AMFConfigurationUpdate "AMFConfigurationUpdate" crate::ngap::AMFConfigurationUpdate; SuccessfulOutcome Successful_AMFConfigurationUpdate "AMFConfigurationUpdateAcknowledge" crate::ngap::AMFConfigurationUpdateAcknowledge; UnsuccessfulOutcome Unsuccessful_AMFConfigurationUpdate "AMFConfigurationUpdateFailure" crate::ngap::AMFConfigurationUpdateFailure; }
    1 AMFStatusIndication { InitiatingMessage Initiating_AMFStatusIndication "AMFStatusIndication" crate::ngap::AMFStatusIndication; }
    2 CellTrafficTrace { InitiatingMessage Initiating_CellTrafficTrace "CellTrafficTrace" crate::ngap::CellTrafficTrace; }
    3 DeactivateTrace { InitiatingMessage Initiating_DeactivateTrace "DeactivateTrace" crate::ngap::DeactivateTrace; }
    4 DownlinkNASTransport { InitiatingMessage Initiating_DownlinkNASTransport "DownlinkNASTransport" crate::ngap::DownlinkNASTransport; }
    5 DownlinkNonUEAssociatedNRPPaTransport { InitiatingMessage Initiating_DownlinkNonUEAssociatedNRPPaTransport "DownlinkNonUEAssociatedNRPPaTransport" crate::ngap::DownlinkNonUEAssociatedNRPPaTransport; }
    6 DownlinkRANConfigurationTransfer { InitiatingMessage Initiating_DownlinkRANConfigurationTransfer "DownlinkRANConfigurationTransfer" crate::ngap::DownlinkRANConfigurationTransfer; }
    7 DownlinkRANStatusTransfer { InitiatingMessage Initiating_DownlinkRANStatusTransfer "DownlinkRANStatusTransfer" crate::ngap::DownlinkRANStatusTransfer; }
    8 DownlinkUEAssociatedNRPPaTransport { InitiatingMessage Initiating_DownlinkUEAssociatedNRPPaTransport "DownlinkUEAssociatedNRPPaTransport" crate::ngap::DownlinkUEAssociatedNRPPaTransport; }
    9 ErrorIndication { InitiatingMessage Initiating_ErrorIndication "ErrorIndication" crate::ngap::ErrorIndication; }
    10 HandoverCancel { InitiatingMessage Initiating_HandoverCancel "HandoverCancel" crate::ngap::HandoverCancel; SuccessfulOutcome Successful_HandoverCancel "HandoverCancelAcknowledge" crate::ngap::HandoverCancelAcknowledge; }
    11 HandoverNotification { InitiatingMessage Initiating_HandoverNotification "HandoverNotify" crate::ngap::HandoverNotify; }
    12 HandoverPreparation { InitiatingMessage Initiating_HandoverPreparation "HandoverRequired" crate::ngap::HandoverRequired; SuccessfulOutcome Successful_HandoverPreparation "HandoverCommand" crate::ngap::HandoverCommand; UnsuccessfulOutcome Unsuccessful_HandoverPreparation "HandoverPreparationFailure" crate::ngap::HandoverPreparationFailure; }
    13 HandoverResourceAllocation { InitiatingMessage Initiating_HandoverResourceAllocation "HandoverRequest" crate::ngap::HandoverRequest; SuccessfulOutcome Successful_HandoverResourceAllocation "HandoverRequestAcknowledge" crate::ngap::HandoverRequestAcknowledge; UnsuccessfulOutcome Unsuccessful_HandoverResourceAllocation "HandoverFailure" crate::ngap::HandoverFailure; }
    14 InitialContextSetup { InitiatingMessage Initiating_InitialContextSetup "InitialContextSetupRequest" crate::ngap::InitialContextSetupRequest; SuccessfulOutcome Successful_InitialContextSetup "InitialContextSetupResponse" crate::ngap::InitialContextSetupResponse; UnsuccessfulOutcome Unsuccessful_InitialContextSetup "InitialContextSetupFailure" crate::ngap::InitialContextSetupFailure; }
    15 InitialUEMessage { InitiatingMessage Initiating_InitialUEMessage "InitialUEMessage" crate::ngap::InitialUEMessage; }
    16 LocationReportingControl { InitiatingMessage Initiating_LocationReportingControl "LocationReportingControl" crate::ngap::LocationReportingControl; }
    17 LocationReportingFailureIndication { InitiatingMessage Initiating_LocationReportingFailureIndication "LocationReportingFailureIndication" crate::ngap::LocationReportingFailureIndication; }
    18 LocationReport { InitiatingMessage Initiating_LocationReport "LocationReport" crate::ngap::LocationReport; }
    19 NASNonDeliveryIndication { InitiatingMessage Initiating_NASNonDeliveryIndication "NASNonDeliveryIndication" crate::ngap::NASNonDeliveryIndication; }
    20 NGReset { InitiatingMessage Initiating_NGReset "NGReset" crate::ngap::NGReset; SuccessfulOutcome Successful_NGReset "NGResetAcknowledge" crate::ngap::NGResetAcknowledge; }
    21 NGSetup { InitiatingMessage Initiating_NGSetup "NGSetupRequest" crate::ngap::NGSetupRequest; SuccessfulOutcome Successful_NGSetup "NGSetupResponse" crate::ngap::NGSetupResponse; UnsuccessfulOutcome Unsuccessful_NGSetup "NGSetupFailure" crate::ngap::NGSetupFailure; }
    22 OverloadStart { InitiatingMessage Initiating_OverloadStart "OverloadStart" crate::ngap::OverloadStart; }
    23 OverloadStop { InitiatingMessage Initiating_OverloadStop "OverloadStop" crate::ngap::OverloadStop; }
    24 Paging { InitiatingMessage Initiating_Paging "Paging" crate::ngap::Paging; }
    25 PathSwitchRequest { InitiatingMessage Initiating_PathSwitchRequest "PathSwitchRequest" crate::ngap::PathSwitchRequest; SuccessfulOutcome Successful_PathSwitchRequest "PathSwitchRequestAcknowledge" crate::ngap::PathSwitchRequestAcknowledge; UnsuccessfulOutcome Unsuccessful_PathSwitchRequest "PathSwitchRequestFailure" crate::ngap::PathSwitchRequestFailure; }
    26 PDUSessionResourceModify { InitiatingMessage Initiating_PDUSessionResourceModify "PDUSessionResourceModifyRequest" crate::ngap::PDUSessionResourceModifyRequest; SuccessfulOutcome Successful_PDUSessionResourceModify "PDUSessionResourceModifyResponse" crate::ngap::PDUSessionResourceModifyResponse; }
    27 PDUSessionResourceModifyIndication { InitiatingMessage Initiating_PDUSessionResourceModifyIndication "PDUSessionResourceModifyIndication" crate::ngap::PDUSessionResourceModifyIndication; SuccessfulOutcome Successful_PDUSessionResourceModifyIndication "PDUSessionResourceModifyConfirm" crate::ngap::PDUSessionResourceModifyConfirm; }
    28 PDUSessionResourceRelease { InitiatingMessage Initiating_PDUSessionResourceRelease "PDUSessionResourceReleaseCommand" crate::ngap::PDUSessionResourceReleaseCommand; SuccessfulOutcome Successful_PDUSessionResourceRelease "PDUSessionResourceReleaseResponse" crate::ngap::PDUSessionResourceReleaseResponse; }
    29 PDUSessionResourceSetup { InitiatingMessage Initiating_PDUSessionResourceSetup "PDUSessionResourceSetupRequest" crate::ngap::PDUSessionResourceSetupRequest; SuccessfulOutcome Successful_PDUSessionResourceSetup "PDUSessionResourceSetupResponse" crate::ngap::PDUSessionResourceSetupResponse; }
    30 PDUSessionResourceNotify { InitiatingMessage Initiating_PDUSessionResourceNotify "PDUSessionResourceNotify" crate::ngap::PDUSessionResourceNotify; }
    31 PrivateMessage { InitiatingMessage Initiating_PrivateMessage "PrivateMessage" crate::ngap::PrivateMessage; }
    32 PWSCancel { InitiatingMessage Initiating_PWSCancel "PWSCancelRequest" crate::ngap::PWSCancelRequest; SuccessfulOutcome Successful_PWSCancel "PWSCancelResponse" crate::ngap::PWSCancelResponse; }
    33 PWSFailureIndication { InitiatingMessage Initiating_PWSFailureIndication "PWSFailureIndication" crate::ngap::PWSFailureIndication; }
    34 PWSRestartIndication { InitiatingMessage Initiating_PWSRestartIndication "PWSRestartIndication" crate::ngap::PWSRestartIndication; }
    35 RANConfigurationUpdate { InitiatingMessage Initiating_RANConfigurationUpdate "RANConfigurationUpdate" crate::ngap::RANConfigurationUpdate; SuccessfulOutcome Successful_RANConfigurationUpdate "RANConfigurationUpdateAcknowledge" crate::ngap::RANConfigurationUpdateAcknowledge; UnsuccessfulOutcome Unsuccessful_RANConfigurationUpdate "RANConfigurationUpdateFailure" crate::ngap::RANConfigurationUpdateFailure; }
    36 RerouteNASRequest { InitiatingMessage Initiating_RerouteNASRequest "RerouteNASRequest" crate::ngap::RerouteNASRequest; }
    37 RRCInactiveTransitionReport { InitiatingMessage Initiating_RRCInactiveTransitionReport "RRCInactiveTransitionReport" crate::ngap::RRCInactiveTransitionReport; }
    38 TraceFailureIndication { InitiatingMessage Initiating_TraceFailureIndication "TraceFailureIndication" crate::ngap::TraceFailureIndication; }
    39 TraceStart { InitiatingMessage Initiating_TraceStart "TraceStart" crate::ngap::TraceStart; }
    40 UEContextModification { InitiatingMessage Initiating_UEContextModification "UEContextModificationRequest" crate::ngap::UEContextModificationRequest; SuccessfulOutcome Successful_UEContextModification "UEContextModificationResponse" crate::ngap::UEContextModificationResponse; UnsuccessfulOutcome Unsuccessful_UEContextModification "UEContextModificationFailure" crate::ngap::UEContextModificationFailure; }
    41 UEContextRelease { InitiatingMessage Initiating_UEContextRelease "UEContextReleaseCommand" crate::ngap::UEContextReleaseCommand; SuccessfulOutcome Successful_UEContextRelease "UEContextReleaseComplete" crate::ngap::UEContextReleaseComplete; }
    42 UEContextReleaseRequest { InitiatingMessage Initiating_UEContextReleaseRequest "UEContextReleaseRequest" crate::ngap::UEContextReleaseRequest; }
    43 UERadioCapabilityCheck { InitiatingMessage Initiating_UERadioCapabilityCheck "UERadioCapabilityCheckRequest" crate::ngap::UERadioCapabilityCheckRequest; SuccessfulOutcome Successful_UERadioCapabilityCheck "UERadioCapabilityCheckResponse" crate::ngap::UERadioCapabilityCheckResponse; }
    44 UERadioCapabilityInfoIndication { InitiatingMessage Initiating_UERadioCapabilityInfoIndication "UERadioCapabilityInfoIndication" crate::ngap::UERadioCapabilityInfoIndication; }
    45 UETNLABindingRelease { InitiatingMessage Initiating_UETNLABindingRelease "UETNLABindingReleaseRequest" crate::ngap::UETNLABindingReleaseRequest; }
    46 UplinkNASTransport { InitiatingMessage Initiating_UplinkNASTransport "UplinkNASTransport" crate::ngap::UplinkNASTransport; }
    47 UplinkNonUEAssociatedNRPPaTransport { InitiatingMessage Initiating_UplinkNonUEAssociatedNRPPaTransport "UplinkNonUEAssociatedNRPPaTransport" crate::ngap::UplinkNonUEAssociatedNRPPaTransport; }
    48 UplinkRANConfigurationTransfer { InitiatingMessage Initiating_UplinkRANConfigurationTransfer "UplinkRANConfigurationTransfer" crate::ngap::UplinkRANConfigurationTransfer; }
    49 UplinkRANStatusTransfer { InitiatingMessage Initiating_UplinkRANStatusTransfer "UplinkRANStatusTransfer" crate::ngap::UplinkRANStatusTransfer; }
    50 UplinkUEAssociatedNRPPaTransport { InitiatingMessage Initiating_UplinkUEAssociatedNRPPaTransport "UplinkUEAssociatedNRPPaTransport" crate::ngap::UplinkUEAssociatedNRPPaTransport; }
    51 WriteReplaceWarning { InitiatingMessage Initiating_WriteReplaceWarning "WriteReplaceWarningRequest" crate::ngap::WriteReplaceWarningRequest; SuccessfulOutcome Successful_WriteReplaceWarning "WriteReplaceWarningResponse" crate::ngap::WriteReplaceWarningResponse; }
    52 SecondaryRATDataUsageReport { InitiatingMessage Initiating_SecondaryRATDataUsageReport "SecondaryRATDataUsageReport" crate::ngap::SecondaryRATDataUsageReport; }
    53 UplinkRIMInformationTransfer { InitiatingMessage Initiating_UplinkRIMInformationTransfer "UplinkRIMInformationTransfer" crate::ngap::UplinkRIMInformationTransfer; }
    54 DownlinkRIMInformationTransfer { InitiatingMessage Initiating_DownlinkRIMInformationTransfer "DownlinkRIMInformationTransfer" crate::ngap::DownlinkRIMInformationTransfer; }
    55 RetrieveUEInformation { InitiatingMessage Initiating_RetrieveUEInformation "RetrieveUEInformation" crate::ngap::RetrieveUEInformation; }
    56 UEInformationTransfer { InitiatingMessage Initiating_UEInformationTransfer "UEInformationTransfer" crate::ngap::UEInformationTransfer; }
    57 RANCPRelocationIndication { InitiatingMessage Initiating_RANCPRelocationIndication "RANCPRelocationIndication" crate::ngap::RANCPRelocationIndication; }
    58 UEContextResume { InitiatingMessage Initiating_UEContextResume "UEContextResumeRequest" crate::ngap::UEContextResumeRequest; SuccessfulOutcome Successful_UEContextResume "UEContextResumeResponse" crate::ngap::UEContextResumeResponse; UnsuccessfulOutcome Unsuccessful_UEContextResume "UEContextResumeFailure" crate::ngap::UEContextResumeFailure; }
    59 UEContextSuspend { InitiatingMessage Initiating_UEContextSuspend "UEContextSuspendRequest" crate::ngap::UEContextSuspendRequest; SuccessfulOutcome Successful_UEContextSuspend "UEContextSuspendResponse" crate::ngap::UEContextSuspendResponse; UnsuccessfulOutcome Unsuccessful_UEContextSuspend "UEContextSuspendFailure" crate::ngap::UEContextSuspendFailure; }
    60 UERadioCapabilityIDMapping { InitiatingMessage Initiating_UERadioCapabilityIDMapping "UERadioCapabilityIDMappingRequest" crate::ngap::UERadioCapabilityIDMappingRequest; SuccessfulOutcome Successful_UERadioCapabilityIDMapping "UERadioCapabilityIDMappingResponse" crate::ngap::UERadioCapabilityIDMappingResponse; }
    61 HandoverSuccess { InitiatingMessage Initiating_HandoverSuccess "HandoverSuccess" crate::ngap::HandoverSuccess; }
    62 UplinkRANEarlyStatusTransfer { InitiatingMessage Initiating_UplinkRANEarlyStatusTransfer "UplinkRANEarlyStatusTransfer" crate::ngap::UplinkRANEarlyStatusTransfer; }
    63 DownlinkRANEarlyStatusTransfer { InitiatingMessage Initiating_DownlinkRANEarlyStatusTransfer "DownlinkRANEarlyStatusTransfer" crate::ngap::DownlinkRANEarlyStatusTransfer; }
    64 AMFCPRelocationIndication { InitiatingMessage Initiating_AMFCPRelocationIndication "AMFCPRelocationIndication" crate::ngap::AMFCPRelocationIndication; }
    65 ConnectionEstablishmentIndication { InitiatingMessage Initiating_ConnectionEstablishmentIndication "ConnectionEstablishmentIndication" crate::ngap::ConnectionEstablishmentIndication; }
    66 BroadcastSessionModification { InitiatingMessage Initiating_BroadcastSessionModification "BroadcastSessionModificationRequest" crate::ngap::BroadcastSessionModificationRequest; SuccessfulOutcome Successful_BroadcastSessionModification "BroadcastSessionModificationResponse" crate::ngap::BroadcastSessionModificationResponse; UnsuccessfulOutcome Unsuccessful_BroadcastSessionModification "BroadcastSessionModificationFailure" crate::ngap::BroadcastSessionModificationFailure; }
    67 BroadcastSessionRelease { InitiatingMessage Initiating_BroadcastSessionRelease "BroadcastSessionReleaseRequest" crate::ngap::BroadcastSessionReleaseRequest; SuccessfulOutcome Successful_BroadcastSessionRelease "BroadcastSessionReleaseResponse" crate::ngap::BroadcastSessionReleaseResponse; }
    68 BroadcastSessionSetup { InitiatingMessage Initiating_BroadcastSessionSetup "BroadcastSessionSetupRequest" crate::ngap::BroadcastSessionSetupRequest; SuccessfulOutcome Successful_BroadcastSessionSetup "BroadcastSessionSetupResponse" crate::ngap::BroadcastSessionSetupResponse; UnsuccessfulOutcome Unsuccessful_BroadcastSessionSetup "BroadcastSessionSetupFailure" crate::ngap::BroadcastSessionSetupFailure; }
    69 DistributionSetup { InitiatingMessage Initiating_DistributionSetup "DistributionSetupRequest" crate::ngap::DistributionSetupRequest; SuccessfulOutcome Successful_DistributionSetup "DistributionSetupResponse" crate::ngap::DistributionSetupResponse; UnsuccessfulOutcome Unsuccessful_DistributionSetup "DistributionSetupFailure" crate::ngap::DistributionSetupFailure; }
    70 DistributionRelease { InitiatingMessage Initiating_DistributionRelease "DistributionReleaseRequest" crate::ngap::DistributionReleaseRequest; SuccessfulOutcome Successful_DistributionRelease "DistributionReleaseResponse" crate::ngap::DistributionReleaseResponse; }
    71 MulticastSessionActivation { InitiatingMessage Initiating_MulticastSessionActivation "MulticastSessionActivationRequest" crate::ngap::MulticastSessionActivationRequest; SuccessfulOutcome Successful_MulticastSessionActivation "MulticastSessionActivationResponse" crate::ngap::MulticastSessionActivationResponse; UnsuccessfulOutcome Unsuccessful_MulticastSessionActivation "MulticastSessionActivationFailure" crate::ngap::MulticastSessionActivationFailure; }
    72 MulticastSessionDeactivation { InitiatingMessage Initiating_MulticastSessionDeactivation "MulticastSessionDeactivationRequest" crate::ngap::MulticastSessionDeactivationRequest; SuccessfulOutcome Successful_MulticastSessionDeactivation "MulticastSessionDeactivationResponse" crate::ngap::MulticastSessionDeactivationResponse; }
    73 MulticastSessionUpdate { InitiatingMessage Initiating_MulticastSessionUpdate "MulticastSessionUpdateRequest" crate::ngap::MulticastSessionUpdateRequest; SuccessfulOutcome Successful_MulticastSessionUpdate "MulticastSessionUpdateResponse" crate::ngap::MulticastSessionUpdateResponse; UnsuccessfulOutcome Unsuccessful_MulticastSessionUpdate "MulticastSessionUpdateFailure" crate::ngap::MulticastSessionUpdateFailure; }
    74 MulticastGroupPaging { InitiatingMessage Initiating_MulticastGroupPaging "MulticastGroupPaging" crate::ngap::MulticastGroupPaging; }
    75 BroadcastSessionReleaseRequired { InitiatingMessage Initiating_BroadcastSessionReleaseRequired "BroadcastSessionReleaseRequired" crate::ngap::BroadcastSessionReleaseRequired; }
    76 TimingSynchronisationStatus { InitiatingMessage Initiating_TimingSynchronisationStatus "TimingSynchronisationStatusRequest" crate::ngap::TimingSynchronisationStatusRequest; SuccessfulOutcome Successful_TimingSynchronisationStatus "TimingSynchronisationStatusResponse" crate::ngap::TimingSynchronisationStatusResponse; UnsuccessfulOutcome Unsuccessful_TimingSynchronisationStatus "TimingSynchronisationStatusFailure" crate::ngap::TimingSynchronisationStatusFailure; }
    77 TimingSynchronisationStatusReport { InitiatingMessage Initiating_TimingSynchronisationStatusReport "TimingSynchronisationStatusReport" crate::ngap::TimingSynchronisationStatusReport; }
    78 MTCommunicationHandling { InitiatingMessage Initiating_MTCommunicationHandling "MTCommunicationHandlingRequest" crate::ngap::MTCommunicationHandlingRequest; SuccessfulOutcome Successful_MTCommunicationHandling "MTCommunicationHandlingResponse" crate::ngap::MTCommunicationHandlingResponse; UnsuccessfulOutcome Unsuccessful_MTCommunicationHandling "MTCommunicationHandlingFailure" crate::ngap::MTCommunicationHandlingFailure; }
    79 RANPagingRequest { InitiatingMessage Initiating_RANPagingRequest "RANPagingRequest" crate::ngap::RANPagingRequest; }
    80 BroadcastSessionTransport { InitiatingMessage Initiating_BroadcastSessionTransport "BroadcastSessionTransportRequest" crate::ngap::BroadcastSessionTransportRequest; SuccessfulOutcome Successful_BroadcastSessionTransport "BroadcastSessionTransportResponse" crate::ngap::BroadcastSessionTransportResponse; UnsuccessfulOutcome Unsuccessful_BroadcastSessionTransport "BroadcastSessionTransportFailure" crate::ngap::BroadcastSessionTransportFailure; }
    81 NGRemoval { InitiatingMessage Initiating_NGRemoval "NGRemovalRequest" crate::ngap::NGRemovalRequest; SuccessfulOutcome Successful_NGRemoval "NGRemovalResponse" crate::ngap::NGRemovalResponse; UnsuccessfulOutcome Unsuccessful_NGRemoval "NGRemovalFailure" crate::ngap::NGRemovalFailure; }
    82 InventoryRequest { InitiatingMessage Initiating_InventoryRequest "InventoryRequest" crate::ngap::InventoryRequest; SuccessfulOutcome Successful_InventoryRequest "InventoryResponse" crate::ngap::InventoryResponse; UnsuccessfulOutcome Unsuccessful_InventoryRequest "InventoryFailure" crate::ngap::InventoryFailure; }
    83 InventoryReport { InitiatingMessage Initiating_InventoryReport "InventoryReport" crate::ngap::InventoryReport; }
    84 CommandRequest { InitiatingMessage Initiating_CommandRequest "CommandRequest" crate::ngap::CommandRequest; SuccessfulOutcome Successful_CommandRequest "CommandResponse" crate::ngap::CommandResponse; UnsuccessfulOutcome Unsuccessful_CommandRequest "CommandFailure" crate::ngap::CommandFailure; }
    85 AIOTSessionRelease { InitiatingMessage Initiating_AIOTSessionRelease "AIOTSessionReleaseCommand" crate::ngap::AIOTSessionReleaseCommand; SuccessfulOutcome Successful_AIOTSessionRelease "AIOTSessionReleaseComplete" crate::ngap::AIOTSessionReleaseComplete; }
    86 AIOTSessionReleaseRequest { InitiatingMessage Initiating_AIOTSessionReleaseRequest "AIOTSessionReleaseRequest" crate::ngap::AIOTSessionReleaseRequest; }
}
ies! {
    0 "AllowedNSSAI" crate::ngap::AllowedNSSAI => AllowedNSSAI;
    1 "AMFName" crate::ngap::AMFName => AMFName;
    2 "AMFOverloadResponse" crate::ngap::OverloadResponse => AMFOverloadResponse OverloadResponse;
    3 "AMFSetID" crate::ngap::AMFSetID => AMFSetID;
    4 "AMF-TNLAssociationFailedToSetupList" crate::ngap::TNLAssociationList => AMF_TNLAssociationFailedToSetupList TNLAssociationList;
    5 "AMF-TNLAssociationSetupList" crate::ngap::AMFTNLAssociationSetupList => AMF_TNLAssociationSetupList AMFTNLAssociationSetupList;
    6 "AMF-TNLAssociationToAddList" crate::ngap::AMFTNLAssociationToAddList => AMF_TNLAssociationToAddList AMFTNLAssociationToAddList;
    7 "AMF-TNLAssociationToRemoveList" crate::ngap::AMFTNLAssociationToRemoveList => AMF_TNLAssociationToRemoveList AMFTNLAssociationToRemoveList;
    8 "AMF-TNLAssociationToUpdateList" crate::ngap::AMFTNLAssociationToUpdateList => AMF_TNLAssociationToUpdateList AMFTNLAssociationToUpdateList;
    9 "AMFTrafficLoadReductionIndication" crate::ngap::TrafficLoadReductionIndication => AMFTrafficLoadReductionIndication TrafficLoadReductionIndication;
    10 "AMF-UE-NGAP-ID" crate::ngap::AMFUENGAPID => AMF_UE_NGAP_ID;
    11 "AssistanceDataForPaging" crate::ngap::AssistanceDataForPaging => AssistanceDataForPaging;
    12 "BroadcastCancelledAreaList" crate::ngap::BroadcastCancelledAreaList => BroadcastCancelledAreaList;
    13 "BroadcastCompletedAreaList" crate::ngap::BroadcastCompletedAreaList => BroadcastCompletedAreaList;
    14 "CancelAllWarningMessages" crate::ngap::CancelAllWarningMessages => CancelAllWarningMessages;
    15 "Cause" crate::ngap::Cause => Cause;
    16 "CellIDListForRestart" crate::ngap::CellIDListForRestart => CellIDListForRestart;
    17 "ConcurrentWarningMessageInd" crate::ngap::ConcurrentWarningMessageInd => ConcurrentWarningMessageInd;
    18 "CoreNetworkAssistanceInformationForInactive" crate::ngap::CoreNetworkAssistanceInformationForInactive => CoreNetworkAssistanceInformationForInactive;
    19 "CriticalityDiagnostics" crate::ngap::CriticalityDiagnostics => CriticalityDiagnostics;
    20 "DataCodingScheme" crate::ngap::DataCodingScheme => DataCodingScheme;
    21 "DefaultPagingDRX" crate::ngap::PagingDRX => DefaultPagingDRX;
    22 "DirectForwardingPathAvailability" crate::ngap::DirectForwardingPathAvailability => DirectForwardingPathAvailability;
    23 "EmergencyAreaIDListForRestart" crate::ngap::EmergencyAreaIDListForRestart => EmergencyAreaIDListForRestart;
    24 "EmergencyFallbackIndicator" crate::ngap::EmergencyFallbackIndicator => EmergencyFallbackIndicator;
    25 "EUTRA-CGI" crate::ngap::EUTRACGI => EUTRA_CGI EUTRACGI;
    26 "FiveG-S-TMSI" crate::ngap::FiveGSTMSI => FiveG_S_TMSI FiveGSTMSI;
    27 "GlobalRANNodeID" crate::ngap::GlobalRANNodeID => GlobalRANNodeID;
    28 "GUAMI" crate::ngap::GUAMI => GUAMI;
    29 "HandoverType" crate::ngap::HandoverType => HandoverType;
    30 "IMSVoiceSupportIndicator" crate::ngap::IMSVoiceSupportIndicator => IMSVoiceSupportIndicator;
    31 "IndexToRFSP" crate::ngap::IndexToRFSP => IndexToRFSP;
    32 "InfoOnRecommendedCellsAndRANNodesForPaging" crate::ngap::InfoOnRecommendedCellsAndRANNodesForPaging => InfoOnRecommendedCellsAndRANNodesForPaging;
    33 "LocationReportingRequestType" crate::ngap::LocationReportingRequestType => LocationReportingRequestType;
    34 "MaskedIMEISV" crate::ngap::MaskedIMEISV => MaskedIMEISV;
    35 "MessageIdentifier" crate::ngap::MessageIdentifier => MessageIdentifier;
    36 "MobilityRestrictionList" crate::ngap::MobilityRestrictionList => MobilityRestrictionList;
    37 "NASC" crate::ngap::NASPDU => NASC;
    38 "NAS-PDU" crate::ngap::NASPDU => NAS_PDU;
    39 "NASSecurityParametersFromNGRAN" crate::ngap::NASSecurityParametersFromNGRAN => NASSecurityParametersFromNGRAN;
    40 "NewAMF-UE-NGAP-ID" crate::ngap::AMFUENGAPID => NewAMF_UE_NGAP_ID;
    41 "NewSecurityContextInd" crate::ngap::NewSecurityContextInd => NewSecurityContextInd;
    42 "NGAP-Message" rasn::types::OctetString => NGAP_Message;
    43 "NGRAN-CGI" crate::ngap::NGRANCGI => NGRAN_CGI NGRANCGI;
    44 "NGRANTraceID" crate::ngap::NGRANTraceID => NGRANTraceID;
    45 "NR-CGI" crate::ngap::NRCGI;
    46 "NRPPa-PDU" crate::ngap::NRPPaPDU => NRPPa_PDU NRPPaPDU;
    47 "NumberOfBroadcastsRequested" crate::ngap::NumberOfBroadcastsRequested => NumberOfBroadcastsRequested;
    48 "OldAMF" crate::ngap::AMFName => OldAMF;
    49 "OverloadStartNSSAIList" crate::ngap::OverloadStartNSSAIList => OverloadStartNSSAIList;
    50 "PagingDRX" crate::ngap::PagingDRX => PagingDRX;
    51 "PagingOrigin" crate::ngap::PagingOrigin => PagingOrigin;
    52 "PagingPriority" crate::ngap::PagingPriority => PagingPriority;
    53 "PDUSessionResourceAdmittedList" crate::ngap::PDUSessionResourceAdmittedList => PDUSessionResourceAdmittedList;
    54 "PDUSessionResourceFailedToModifyListModRes" crate::ngap::PDUSessionResourceFailedToModifyListModRes => PDUSessionResourceFailedToModifyListModRes;
    55 "PDUSessionResourceFailedToSetupListCxtRes" crate::ngap::PDUSessionResourceFailedToSetupListCxtRes => PDUSessionResourceFailedToSetupListCxtRes;
    56 "PDUSessionResourceFailedToSetupListHOAck" crate::ngap::PDUSessionResourceFailedToSetupListHOAck => PDUSessionResourceFailedToSetupListHOAck;
    57 "PDUSessionResourceFailedToSetupListPSReq" crate::ngap::PDUSessionResourceFailedToSetupListPSReq => PDUSessionResourceFailedToSetupListPSReq;
    58 "PDUSessionResourceFailedToSetupListSURes" crate::ngap::PDUSessionResourceFailedToSetupListSURes => PDUSessionResourceFailedToSetupListSURes;
    59 "PDUSessionResourceHandoverList" crate::ngap::PDUSessionResourceHandoverList => PDUSessionResourceHandoverList;
    60 "PDUSessionResourceListCxtRelCpl" crate::ngap::PDUSessionResourceListCxtRelCpl => PDUSessionResourceListCxtRelCpl;
    61 "PDUSessionResourceListHORqd" crate::ngap::PDUSessionResourceListHORqd => PDUSessionResourceListHORqd;
    62 "PDUSessionResourceModifyListModCfm" crate::ngap::PDUSessionResourceModifyListModCfm => PDUSessionResourceModifyListModCfm;
    63 "PDUSessionResourceModifyListModInd" crate::ngap::PDUSessionResourceModifyListModInd => PDUSessionResourceModifyListModInd;
    64 "PDUSessionResourceModifyListModReq" crate::ngap::PDUSessionResourceModifyListModReq => PDUSessionResourceModifyListModReq;
    65 "PDUSessionResourceModifyListModRes" crate::ngap::PDUSessionResourceModifyListModRes => PDUSessionResourceModifyListModRes;
    66 "PDUSessionResourceNotifyList" crate::ngap::PDUSessionResourceNotifyList => PDUSessionResourceNotifyList;
    67 "PDUSessionResourceReleasedListNot" crate::ngap::PDUSessionResourceReleasedListNot => PDUSessionResourceReleasedListNot;
    68 "PDUSessionResourceReleasedListPSAck" crate::ngap::PDUSessionResourceReleasedListPSAck => PDUSessionResourceReleasedListPSAck;
    69 "PDUSessionResourceReleasedListPSFail" crate::ngap::PDUSessionResourceReleasedListPSFail => PDUSessionResourceReleasedListPSFail;
    70 "PDUSessionResourceReleasedListRelRes" crate::ngap::PDUSessionResourceReleasedListRelRes => PDUSessionResourceReleasedListRelRes;
    71 "PDUSessionResourceSetupListCxtReq" crate::ngap::PDUSessionResourceSetupListCxtReq => PDUSessionResourceSetupListCxtReq;
    72 "PDUSessionResourceSetupListCxtRes" crate::ngap::PDUSessionResourceSetupListCxtRes => PDUSessionResourceSetupListCxtRes;
    73 "PDUSessionResourceSetupListHOReq" crate::ngap::PDUSessionResourceSetupListHOReq => PDUSessionResourceSetupListHOReq;
    74 "PDUSessionResourceSetupListSUReq" crate::ngap::PDUSessionResourceSetupListSUReq => PDUSessionResourceSetupListSUReq;
    75 "PDUSessionResourceSetupListSURes" crate::ngap::PDUSessionResourceSetupListSURes => PDUSessionResourceSetupListSURes;
    76 "PDUSessionResourceToBeSwitchedDLList" crate::ngap::PDUSessionResourceToBeSwitchedDLList => PDUSessionResourceToBeSwitchedDLList;
    77 "PDUSessionResourceSwitchedList" crate::ngap::PDUSessionResourceSwitchedList => PDUSessionResourceSwitchedList;
    78 "PDUSessionResourceToReleaseListHOCmd" crate::ngap::PDUSessionResourceToReleaseListHOCmd => PDUSessionResourceToReleaseListHOCmd;
    79 "PDUSessionResourceToReleaseListRelCmd" crate::ngap::PDUSessionResourceToReleaseListRelCmd => PDUSessionResourceToReleaseListRelCmd;
    80 "PLMNSupportList" crate::ngap::PLMNSupportList => PLMNSupportList;
    81 "PWSFailedCellIDList" crate::ngap::PWSFailedCellIDList => PWSFailedCellIDList;
    82 "RANNodeName" crate::ngap::RANNodeName => RANNodeName;
    83 "RANPagingPriority" crate::ngap::RANPagingPriority => RANPagingPriority;
    84 "RANStatusTransfer-TransparentContainer" crate::ngap::RANStatusTransferTransparentContainer => RANStatusTransfer_TransparentContainer RANStatusTransferTransparentContainer;
    85 "RAN-UE-NGAP-ID" crate::ngap::RANUENGAPID => RAN_UE_NGAP_ID RANUENGAPID;
    86 "RelativeAMFCapacity" crate::ngap::RelativeAMFCapacity => RelativeAMFCapacity;
    87 "RepetitionPeriod" crate::ngap::RepetitionPeriod => RepetitionPeriod;
    88 "ResetType" crate::ngap::ResetType => ResetType;
    89 "RoutingID" crate::ngap::RoutingID => RoutingID;
    90 "RRCEstablishmentCause" crate::ngap::RRCEstablishmentCause => RRCEstablishmentCause;
    91 "RRCInactiveTransitionReportRequest" crate::ngap::RRCInactiveTransitionReportRequest => RRCInactiveTransitionReportRequest;
    92 "RRCState" crate::ngap::RRCState => RRCState;
    93 "SecurityContext" crate::ngap::SecurityContext => SecurityContext;
    94 "SecurityKey" crate::ngap::SecurityKey => SecurityKey;
    95 "SerialNumber" crate::ngap::SerialNumber => SerialNumber;
    96 "ServedGUAMIList" crate::ngap::ServedGUAMIList => ServedGUAMIList;
    98 "SONConfigurationTransferDL" crate::ngap::SONConfigurationTransfer => SONConfigurationTransferDL;
    99 "SONConfigurationTransferUL" crate::ngap::SONConfigurationTransfer => SONConfigurationTransferUL;
    100 "SourceAMF-UE-NGAP-ID" crate::ngap::AMFUENGAPID => SourceAMF_UE_NGAP_ID;
    101 "SourceToTarget-TransparentContainer" crate::ngap::SourceToTargetTransparentContainer => SourceToTarget_TransparentContainer SourceToTargetTransparentContainer;
    102 "SupportedTAList" crate::ngap::SupportedTAList => SupportedTAList;
    103 "TAIListForPaging" crate::ngap::TAIListForPaging => TAIListForPaging;
    104 "TAIListForRestart" crate::ngap::TAIListForRestart => TAIListForRestart;
    105 "TargetID" crate::ngap::TargetID => TargetID;
    106 "TargetToSource-TransparentContainer" crate::ngap::TargetToSourceTransparentContainer => TargetToSource_TransparentContainer TargetToSourceTransparentContainer;
    107 "TimeToWait" crate::ngap::TimeToWait => TimeToWait;
    108 "TraceActivation" crate::ngap::TraceActivation => TraceActivation;
    109 "TraceCollectionEntityIPAddress" crate::ngap::TransportLayerAddress => TraceCollectionEntityIPAddress TransportLayerAddress;
    110 "UEAggregateMaximumBitRate" crate::ngap::UEAggregateMaximumBitRate => UEAggregateMaximumBitRate;
    111 "UE-associatedLogicalNG-connectionList" crate::ngap::UEAssociatedLogicalNGConnectionList => UE_associatedLogicalNG_connectionList UEAssociatedLogicalNGConnectionList;
    112 "UEContextRequest" crate::ngap::UEContextRequest => UEContextRequest;
    114 "UE-NGAP-IDs" crate::ngap::UENGAPIDs => UE_NGAP_IDs UENGAPIDs;
    115 "UEPagingIdentity" crate::ngap::UEPagingIdentity => UEPagingIdentity;
    116 "UEPresenceInAreaOfInterestList" crate::ngap::UEPresenceInAreaOfInterestList => UEPresenceInAreaOfInterestList;
    117 "UERadioCapability" crate::ngap::UERadioCapability => UERadioCapability;
    118 "UERadioCapabilityForPaging" crate::ngap::UERadioCapabilityForPaging => UERadioCapabilityForPaging;
    119 "UESecurityCapabilities" crate::ngap::UESecurityCapabilities => UESecurityCapabilities;
    120 "UnavailableGUAMIList" crate::ngap::UnavailableGUAMIList => UnavailableGUAMIList;
    121 "UserLocationInformation" crate::ngap::UserLocationInformation => UserLocationInformation;
    122 "WarningAreaList" crate::ngap::WarningAreaList => WarningAreaList;
    123 "WarningMessageContents" crate::ngap::WarningMessageContents => WarningMessageContents;
    124 "WarningSecurityInfo" crate::ngap::WarningSecurityInfo => WarningSecurityInfo;
    125 "WarningType" crate::ngap::WarningType => WarningType;
    126 "AdditionalUL-NGU-UP-TNLInformation" crate::ngap::UPTransportLayerInformationList => AdditionalUL_NGU_UP_TNLInformation;
    127 "DataForwardingNotPossible" crate::ngap::DataForwardingNotPossible => DataForwardingNotPossible;
    128 "DL-NGU-UP-TNLInformation" crate::ngap::UPTransportLayerInformation;
    129 "NetworkInstance" crate::ngap::NetworkInstance => NetworkInstance;
    130 "PDUSessionAggregateMaximumBitRate" crate::ngap::PDUSessionAggregateMaximumBitRate => PDUSessionAggregateMaximumBitRate;
    131 "PDUSessionResourceFailedToModifyListModCfm" crate::ngap::PDUSessionResourceFailedToModifyListModCfm => PDUSessionResourceFailedToModifyListModCfm;
    132 "PDUSessionResourceFailedToSetupListCxtFail" crate::ngap::PDUSessionResourceFailedToSetupListCxtFail => PDUSessionResourceFailedToSetupListCxtFail;
    133 "PDUSessionResourceListCxtRelReq" crate::ngap::PDUSessionResourceListCxtRelReq => PDUSessionResourceListCxtRelReq;
    134 "PDUSessionType" crate::ngap::PDUSessionType => PDUSessionType;
    135 "QosFlowAddOrModifyRequestList" crate::ngap::QosFlowAddOrModifyRequestList => QosFlowAddOrModifyRequestList;
    136 "QosFlowSetupRequestList" crate::ngap::QosFlowSetupRequestList => QosFlowSetupRequestList;
    137 "QosFlowToReleaseList" crate::ngap::QosFlowListWithCause => QosFlowToReleaseList;
    138 "SecurityIndication" crate::ngap::SecurityIndication => SecurityIndication;
    139 "UL-NGU-UP-TNLInformation" crate::ngap::UPTransportLayerInformation => UL_NGU_UP_TNLInformation;
    140 "UL-NGU-UP-TNLModifyList" crate::ngap::ULNGUUPTNLModifyList => UL_NGU_UP_TNLModifyList ULNGUUPTNLModifyList;
    141 "WarningAreaCoordinates" crate::ngap::WarningAreaCoordinates => WarningAreaCoordinates;
    142 "PDUSessionResourceSecondaryRATUsageList" crate::ngap::PDUSessionResourceSecondaryRATUsageList => PDUSessionResourceSecondaryRATUsageList;
    143 "HandoverFlag" crate::ngap::HandoverFlag => HandoverFlag;
    144 "SecondaryRATUsageInformation" crate::ngap::SecondaryRATUsageInformation;
    145 "PDUSessionResourceReleaseResponseTransfer" rasn::types::OctetString, crate::ngap::PDUSessionResourceReleaseResponseTransfer;
    146 "RedirectionVoiceFallback" crate::ngap::RedirectionVoiceFallback => RedirectionVoiceFallback;
    147 "UERetentionInformation" crate::ngap::UERetentionInformation => UERetentionInformation;
    148 "S-NSSAI" crate::ngap::SNSSAI => S_NSSAI SNSSAI;
    149 "PSCellInformation" crate::ngap::NGRANCGI;
    150 "LastEUTRAN-PLMNIdentity" crate::ngap::PLMNIdentity;
    151 "MaximumIntegrityProtectedDataRate-DL" crate::ngap::MaximumIntegrityProtectedDataRate;
    152 "AdditionalDLForwardingUPTNLInformation" crate::ngap::QosFlowPerTNLInformationList;
    153 "AdditionalDLUPTNLInformationForHOList" crate::ngap::AdditionalDLUPTNLInformationForHOList;
    154 "AdditionalNGU-UP-TNLInformation" crate::ngap::UPTransportLayerInformationPairList;
    155 "AdditionalDLQosFlowPerTNLInformation" crate::ngap::QosFlowPerTNLInformationList;
    156 "SecurityResult" crate::ngap::SecurityResult;
    157 "ENDC-SONConfigurationTransferDL" crate::ngap::ENDCSONConfigurationTransfer => ENDC_SONConfigurationTransferDL;
    158 "ENDC-SONConfigurationTransferUL" crate::ngap::ENDCSONConfigurationTransfer => ENDC_SONConfigurationTransferUL;
    159 "OldAssociatedQosFlowList-ULendmarkerexpected" crate::ngap::AssociatedQosFlowList;
    160 "CNTypeRestrictionsForEquivalent" crate::ngap::CNTypeRestrictionsForEquivalent;
    161 "CNTypeRestrictionsForServing" crate::ngap::CNTypeRestrictionsForServing;
    162 "NewGUAMI" crate::ngap::GUAMI => NewGUAMI;
    163 "ULForwarding" crate::ngap::ULForwarding;
    164 "ULForwardingUP-TNLInformation" crate::ngap::UPTransportLayerInformation;
    165 "CNAssistedRANTuning" crate::ngap::CNAssistedRANTuning => CNAssistedRANTuning;
    166 "CommonNetworkInstance" crate::ngap::CommonNetworkInstance => CommonNetworkInstance;
    167 "NGRAN-TNLAssociationToRemoveList" crate::ngap::NGRANTNLAssociationToRemoveList => NGRAN_TNLAssociationToRemoveList NGRANTNLAssociationToRemoveList;
    168 "TNLAssociationTransportLayerAddressNGRAN" crate::ngap::CPTransportLayerInformation;
    169 "EndpointIPAddressAndPort" crate::ngap::EndpointIPAddressAndPort => EndpointIPAddressAndPort;
    170 "LocationReportingAdditionalInfo" crate::ngap::LocationReportingAdditionalInfo;
    171 "SourceToTarget-AMFInformationReroute" crate::ngap::SourceToTargetAMFInformationReroute => SourceToTarget_AMFInformationReroute SourceToTargetAMFInformationReroute;
    172 "AdditionalULForwardingUPTNLInformation" crate::ngap::UPTransportLayerInformationList;
    173 "SCTP-TLAs" crate::ngap::SCTPTLAs;
    174 "SelectedPLMNIdentity" crate::ngap::PLMNIdentity => SelectedPLMNIdentity PLMNIdentity;
    175 "RIMInformationTransfer" crate::ngap::RIMInformationTransfer => RIMInformationTransfer;
    176 "GUAMIType" crate::ngap::GUAMIType => GUAMIType;
    177 "SRVCCOperationPossible" crate::ngap::SRVCCOperationPossible => SRVCCOperationPossible;
    178 "TargetRNC-ID" crate::ngap::TargetRNCID => TargetRNC_ID TargetRNCID;
    179 "RAT-Information" crate::ngap::RATInformation;
    180 "ExtendedRATRestrictionInformation" crate::ngap::ExtendedRATRestrictionInformation;
    181 "QosMonitoringRequest" crate::ngap::QosMonitoringRequest;
    182 "SgNB-UE-X2AP-ID" crate::ngap::SgNBUEX2APID;
    183 "AdditionalRedundantDL-NGU-UP-TNLInformation" crate::ngap::UPTransportLayerInformation;
    184 "AdditionalRedundantDLQosFlowPerTNLInformation" crate::ngap::QosFlowPerTNLInformationList;
    185 "AdditionalRedundantNGU-UP-TNLInformation" crate::ngap::UPTransportLayerInformationPairList;
    186 "AdditionalRedundantUL-NGU-UP-TNLInformation" crate::ngap::UPTransportLayerInformationList => AdditionalRedundantUL_NGU_UP_TNLInformation;
    187 "CNPacketDelayBudgetDL" crate::ngap::ExtendedPacketDelayBudget;
    188 "CNPacketDelayBudgetUL" crate::ngap::ExtendedPacketDelayBudget;
    189 "ExtendedPacketDelayBudget" crate::ngap::ExtendedPacketDelayBudget;
    190 "RedundantCommonNetworkInstance" crate::ngap::CommonNetworkInstance => RedundantCommonNetworkInstance;
    191 "RedundantDL-NGU-TNLInformationReused" crate::ngap::DLNGUTNLInformationReused;
    192 "RedundantDL-NGU-UP-TNLInformation" crate::ngap::UPTransportLayerInformation;
    193 "RedundantDLQosFlowPerTNLInformation" crate::ngap::QosFlowPerTNLInformation;
    194 "RedundantQosFlowIndicator" crate::ngap::RedundantQosFlowIndicator;
    195 "RedundantUL-NGU-UP-TNLInformation" crate::ngap::UPTransportLayerInformation => RedundantUL_NGU_UP_TNLInformation;
    196 "TSCTrafficCharacteristics" crate::ngap::TSCTrafficCharacteristics;
    197 "RedundantPDUSessionInformation" crate::ngap::RedundantPDUSessionInformation => RedundantPDUSessionInformation;
    198 "UsedRSNInformation" crate::ngap::RedundantPDUSessionInformation;
    199 "IAB-Authorized" crate::ngap::IABAuthorized => IAB_Authorized IABAuthorized;
    200 "IAB-Supported" crate::ngap::IABSupported => IAB_Supported IABSupported;
    201 "IABNodeIndication" crate::ngap::IABNodeIndication => IABNodeIndication;
    202 "NB-IoT-PagingDRX" crate::ngap::NBIoTPagingDRX => NB_IoT_PagingDRX NBIoTPagingDRX;
    203 "NB-IoT-Paging-eDRXInfo" crate::ngap::NBIoTPagingEDRXInfo => NB_IoT_Paging_eDRXInfo NBIoTPagingEDRXInfo;
    204 "NB-IoT-DefaultPagingDRX" crate::ngap::NBIoTDefaultPagingDRX => NB_IoT_DefaultPagingDRX NBIoTDefaultPagingDRX;
    205 "Enhanced-CoverageRestriction" crate::ngap::EnhancedCoverageRestriction => Enhanced_CoverageRestriction EnhancedCoverageRestriction;
    206 "Extended-ConnectedTime" crate::ngap::ExtendedConnectedTime => Extended_ConnectedTime ExtendedConnectedTime;
    207 "PagingAssisDataforCEcapabUE" crate::ngap::PagingAssisDataforCEcapabUE => PagingAssisDataforCEcapabUE;
    208 "WUS-Assistance-Information" crate::ngap::WUSAssistanceInformation => WUS_Assistance_Information WUSAssistanceInformation;
    209 "UE-DifferentiationInfo" crate::ngap::UEDifferentiationInfo => UE_DifferentiationInfo UEDifferentiationInfo;
    210 "NB-IoT-UEPriority" crate::ngap::NBIoTUEPriority => NB_IoT_UEPriority NBIoTUEPriority;
    211 "UL-CP-SecurityInformation" crate::ngap::ULCPSecurityInformation => UL_CP_SecurityInformation ULCPSecurityInformation;
    212 "DL-CP-SecurityInformation" crate::ngap::DLCPSecurityInformation => DL_CP_SecurityInformation DLCPSecurityInformation;
    213 "TAI" crate::ngap::TAI => TAI;
    214 "UERadioCapabilityForPagingOfNB-IoT" crate::ngap::UERadioCapabilityForPagingOfNBIoT;
    215 "LTEV2XServicesAuthorized" crate::ngap::LTEV2XServicesAuthorized => LTEV2XServicesAuthorized;
    216 "NRV2XServicesAuthorized" crate::ngap::NRV2XServicesAuthorized => NRV2XServicesAuthorized;
    217 "LTEUESidelinkAggregateMaximumBitrate" crate::ngap::LTEUESidelinkAggregateMaximumBitrate => LTEUESidelinkAggregateMaximumBitrate;
    218 "NRUESidelinkAggregateMaximumBitrate" crate::ngap::NRUESidelinkAggregateMaximumBitrate => NRUESidelinkAggregateMaximumBitrate;
    219 "PC5QoSParameters" crate::ngap::PC5QoSParameters => PC5QoSParameters;
    220 "AlternativeQoSParaSetList" crate::ngap::AlternativeQoSParaSetList;
    221 "CurrentQoSParaSetIndex";
    222 "CEmodeBrestricted" crate::ngap::CEmodeBrestricted => CEmodeBrestricted;
    223 "EUTRA-PagingeDRXInformation" crate::ngap::EUTRAPagingeDRXInformation => EUTRA_PagingeDRXInformation EUTRAPagingeDRXInformation;
    224 "CEmodeBSupport-Indicator" crate::ngap::CEmodeBSupportIndicator => CEmodeBSupport_Indicator CEmodeBSupportIndicator;
    225 "LTEM-Indication" crate::ngap::LTEMIndication => LTEM_Indication LTEMIndication;
    226 "EndIndication" crate::ngap::EndIndication => EndIndication;
    227 "EDT-Session" crate::ngap::EDTSession => EDT_Session EDTSession;
    228 "UECapabilityInfoRequest" crate::ngap::UECapabilityInfoRequest => UECapabilityInfoRequest;
    229 "PDUSessionResourceFailedToResumeListRESReq" crate::ngap::PDUSessionResourceFailedToResumeListRESReq => PDUSessionResourceFailedToResumeListRESReq;
    230 "PDUSessionResourceFailedToResumeListRESRes" crate::ngap::PDUSessionResourceFailedToResumeListRESRes => PDUSessionResourceFailedToResumeListRESRes;
    231 "PDUSessionResourceSuspendListSUSReq" crate::ngap::PDUSessionResourceSuspendListSUSReq => PDUSessionResourceSuspendListSUSReq;
    232 "PDUSessionResourceResumeListRESReq" crate::ngap::PDUSessionResourceResumeListRESReq => PDUSessionResourceResumeListRESReq;
    233 "PDUSessionResourceResumeListRESRes" crate::ngap::PDUSessionResourceResumeListRESRes => PDUSessionResourceResumeListRESRes;
    234 "UE-UP-CIoT-Support" crate::ngap::UEUPCIoTSupport => UE_UP_CIoT_Support UEUPCIoTSupport;
    235 "Suspend-Request-Indication" crate::ngap::SuspendRequestIndication => Suspend_Request_Indication SuspendRequestIndication;
    236 "Suspend-Response-Indication" crate::ngap::SuspendResponseIndication => Suspend_Response_Indication SuspendResponseIndication;
    237 "RRC-Resume-Cause" crate::ngap::RRCEstablishmentCause => RRC_Resume_Cause;
    238 "RGLevelWirelineAccessCharacteristics" crate::ngap::RGLevelWirelineAccessCharacteristics => RGLevelWirelineAccessCharacteristics;
    239 "W-AGFIdentityInformation" rasn::types::OctetString => W_AGFIdentityInformation;
    240 "GlobalTNGF-ID" crate::ngap::GlobalTNGFID => GlobalTNGF_ID GlobalTNGFID;
    241 "GlobalTWIF-ID" crate::ngap::GlobalTWIFID => GlobalTWIF_ID GlobalTWIFID;
    242 "GlobalW-AGF-ID" crate::ngap::GlobalWAGFID => GlobalW_AGF_ID GlobalWAGFID;
    243 "UserLocationInformationW-AGF" crate::ngap::UserLocationInformationWAGF => UserLocationInformationW_AGF UserLocationInformationWAGF;
    244 "UserLocationInformationTNGF" crate::ngap::UserLocationInformationTNGF => UserLocationInformationTNGF;
    245 "AuthenticatedIndication" crate::ngap::AuthenticatedIndication => AuthenticatedIndication;
    246 "TNGFIdentityInformation" rasn::types::OctetString => TNGFIdentityInformation;
    247 "TWIFIdentityInformation" rasn::types::OctetString => TWIFIdentityInformation;
    248 "UserLocationInformationTWIF" crate::ngap::UserLocationInformationTWIF => UserLocationInformationTWIF;
    249 "DataForwardingResponseERABList" crate::ngap::DataForwardingResponseERABList;
    250 "IntersystemSONConfigurationTransferDL" crate::ngap::IntersystemSONConfigurationTransfer => IntersystemSONConfigurationTransferDL;
    251 "IntersystemSONConfigurationTransferUL" crate::ngap::IntersystemSONConfigurationTransfer => IntersystemSONConfigurationTransferUL;
    252 "SONInformationReport" crate::ngap::SONInformationReport => SONInformationReport;
    253 "UEHistoryInformationFromTheUE" crate::ngap::UEHistoryInformationFromTheUE;
    254 "ManagementBasedMDTPLMNList" crate::ngap::MDTPLMNList => ManagementBasedMDTPLMNList MDTPLMNList;
    255 "MDTConfiguration" crate::ngap::MDTConfiguration;
    256 "PrivacyIndicator" crate::ngap::PrivacyIndicator => PrivacyIndicator;
    257 "TraceCollectionEntityURI" crate::ngap::URIAddress => TraceCollectionEntityURI URIAddress;
    258 "NPN-Support" crate::ngap::NPNSupport;
    259 "NPN-AccessInformation" crate::ngap::NPNAccessInformation => NPN_AccessInformation NPNAccessInformation;
    260 "NPN-PagingAssistanceInformation" crate::ngap::NPNPagingAssistanceInformation;
    261 "NPN-MobilityInformation" crate::ngap::NPNMobilityInformation;
    262 "TargettoSource-Failure-TransparentContainer" crate::ngap::TargettoSourceFailureTransparentContainer => TargettoSource_Failure_TransparentContainer TargettoSourceFailureTransparentContainer;
    263 "NID" crate::ngap::NID;
    264 "UERadioCapabilityID" crate::ngap::UERadioCapabilityID => UERadioCapabilityID;
    265 "UERadioCapability-EUTRA-Format" crate::ngap::UERadioCapability => UERadioCapability_EUTRA_Format;
    266 "DAPSRequestInfo" crate::ngap::DAPSRequestInfo;
    267 "DAPSResponseInfoList" crate::ngap::DAPSResponseInfoList;
    268 "EarlyStatusTransfer-TransparentContainer" crate::ngap::EarlyStatusTransferTransparentContainer => EarlyStatusTransfer_TransparentContainer EarlyStatusTransferTransparentContainer;
    269 "NotifySourceNGRANNode" crate::ngap::NotifySourceNGRANNode => NotifySourceNGRANNode;
    270 "ExtendedSliceSupportList" crate::ngap::ExtendedSliceSupportList;
    271 "ExtendedTAISliceSupportList" crate::ngap::ExtendedSliceSupportList;
    272 "ConfiguredTACIndication" crate::ngap::ConfiguredTACIndication;
    273 "Extended-RANNodeName" crate::ngap::ExtendedRANNodeName => Extended_RANNodeName ExtendedRANNodeName;
    274 "Extended-AMFName" crate::ngap::ExtendedAMFName => Extended_AMFName;
    275 "GlobalCable-ID" crate::ngap::GlobalCableID => GlobalCable_ID GlobalCableID;
    276 "QosMonitoringReportingFrequency" crate::ngap::QosMonitoringReportingFrequency;
    277 "QosFlowParametersList" crate::ngap::QosFlowParametersList;
    278 "QosFlowFeedbackList" crate::ngap::QosFlowFeedbackList;
    279 "BurstArrivalTimeDownlink" crate::ngap::BurstArrivalTime;
    280 "ExtendedUEIdentityIndexValue" crate::ngap::ExtendedUEIdentityIndexValue;
    281 "PduSessionExpectedUEActivityBehaviour" crate::ngap::ExpectedUEActivityBehaviour;
    282 "MicoAllPLMN" crate::ngap::MicoAllPLMN;
    283 "QosFlowFailedToSetupList" crate::ngap::QosFlowListWithCause;
    284 "SourceTNLAddrInfo" crate::ngap::TransportLayerAddress;
    285 "ExtendedReportIntervalMDT" crate::ngap::ExtendedReportIntervalMDT;
    286 "SourceNodeID" crate::ngap::SourceNodeID;
    287 "NRNTNTAIInformation" crate::ngap::NRNTNTAIInformation;
    288 "UEContextReferenceAtSource" crate::ngap::RANUENGAPID;
    289 "LastVisitedPSCellList" crate::ngap::LastVisitedPSCellList;
    290 "IntersystemSONInformationRequest" crate::ngap::IntersystemSONInformationRequest => IntersystemSONInformationRequest;
    291 "IntersystemSONInformationReply" crate::ngap::IntersystemSONInformationReply => IntersystemSONInformationReply;
    292 "EnergySavingIndication" crate::ngap::IntersystemCellStateIndication => EnergySavingIndication IntersystemCellStateIndication;
    293 "IntersystemResourceStatusUpdate" crate::ngap::IntersystemResourceStatusReport => IntersystemResourceStatusUpdate IntersystemResourceStatusReport;
    294 "SuccessfulHandoverReportList" crate::ngap::SuccessfulHandoverReportList => SuccessfulHandoverReportList;
    295 "MBS-AreaSessionID" crate::ngap::MBSAreaSessionID => MBS_AreaSessionID MBSAreaSessionID;
    297 "MBS-QoSFlowsToBeSetupModList" crate::ngap::MBSQoSFlowsToBeSetupList => MBS_QoSFlowsToBeSetupModList MBSQoSFlowsToBeSetupList;
    298 "MBS-ServiceArea" crate::ngap::MBSServiceArea => MBS_ServiceArea MBSServiceArea;
    299 "MBS-SessionID" crate::ngap::MBSSessionID => MBS_SessionID MBSSessionID;
    300 "MBS-DistributionReleaseRequestTransfer" rasn::types::OctetString, crate::ngap::MBSDistributionReleaseRequestTransfer => MBS_DistributionReleaseRequestTransfer;
    301 "MBS-DistributionSetupRequestTransfer" rasn::types::OctetString, crate::ngap::MBSDistributionSetupRequestTransfer => MBS_DistributionSetupRequestTransfer;
    302 "MBS-DistributionSetupResponseTransfer" rasn::types::OctetString, crate::ngap::MBSDistributionSetupResponseTransfer => MBS_DistributionSetupResponseTransfer;
    303 "MBS-DistributionSetupUnsuccessfulTransfer" rasn::types::OctetString, crate::ngap::MBSDistributionSetupUnsuccessfulTransfer => MBS_DistributionSetupUnsuccessfulTransfer;
    304 "MulticastSessionActivationRequestTransfer" rasn::types::OctetString, crate::ngap::MulticastSessionActivationRequestTransfer => MulticastSessionActivationRequestTransfer;
    305 "MulticastSessionDeactivationRequestTransfer" rasn::types::OctetString, crate::ngap::MulticastSessionDeactivationRequestTransfer => MulticastSessionDeactivationRequestTransfer;
    306 "MulticastSessionUpdateRequestTransfer" rasn::types::OctetString, crate::ngap::MulticastSessionUpdateRequestTransfer => MulticastSessionUpdateRequestTransfer;
    307 "MulticastGroupPagingAreaList" crate::ngap::MulticastGroupPagingAreaList => MulticastGroupPagingAreaList;
    309 "MBS-SupportIndicator" crate::ngap::MBSSupportIndicator;
    310 "MBSSessionFailedtoSetupList" crate::ngap::MBSSessionFailedtoSetupList;
    311 "MBSSessionFailedtoSetuporModifyList" crate::ngap::MBSSessionFailedtoSetupList;
    312 "MBSSessionSetupResponseList" crate::ngap::MBSSessionSetupResponseList;
    313 "MBSSessionSetuporModifyResponseList" crate::ngap::MBSSessionSetupResponseList;
    314 "MBSSessionSetupFailureTransfer" rasn::types::OctetString, crate::ngap::MBSSessionSetupOrModFailureTransfer => MBSSessionSetupFailureTransfer;
    315 "MBSSessionSetupRequestTransfer" rasn::types::OctetString, crate::ngap::MBSSessionSetupOrModRequestTransfer => MBSSessionSetupRequestTransfer;
    316 "MBSSessionSetupResponseTransfer" rasn::types::OctetString, crate::ngap::MBSSessionSetupOrModResponseTransfer => MBSSessionSetupResponseTransfer;
    317 "MBSSessionToReleaseList" crate::ngap::MBSSessionToReleaseList => MBSSessionToReleaseList;
    318 "MBSSessionSetupRequestList" crate::ngap::MBSSessionSetupRequestList => MBSSessionSetupRequestList;
    319 "MBSSessionSetuporModifyRequestList" crate::ngap::MBSSessionSetuporModifyRequestList => MBSSessionSetuporModifyRequestList;
    323 "MBS-ActiveSessionInformation-SourcetoTargetList" crate::ngap::MBSActiveSessionInformationSourcetoTargetList;
    324 "MBS-ActiveSessionInformation-TargettoSourceList" crate::ngap::MBSActiveSessionInformationTargettoSourceList;
    325 "OnboardingSupport" crate::ngap::OnboardingSupport;
    326 "TimeSyncAssistanceInfo" crate::ngap::TimeSyncAssistanceInfo => TimeSyncAssistanceInfo;
    327 "SurvivalTime" crate::ngap::SurvivalTime;
    328 "QMCConfigInfo" crate::ngap::QMCConfigInfo => QMCConfigInfo;
    329 "QMCDeactivation" crate::ngap::QMCDeactivation => QMCDeactivation;
    331 "PDUSessionPairID" crate::ngap::PDUSessionPairID;
    332 "NR-PagingeDRXInformation" crate::ngap::NRPagingeDRXInformation => NR_PagingeDRXInformation NRPagingeDRXInformation;
    333 "RedCapIndication" crate::ngap::RedCapIndication => RedCapIndication;
    334 "TargetNSSAIInformation" crate::ngap::TargetNSSAIInformation => TargetNSSAIInformation;
    335 "UESliceMaximumBitRateList" crate::ngap::UESliceMaximumBitRateList => UESliceMaximumBitRateList;
    336 "M4ReportAmount" crate::ngap::M4ReportAmountMDT;
    337 "M5ReportAmount" crate::ngap::M5ReportAmountMDT;
    338 "M6ReportAmount" crate::ngap::M6ReportAmountMDT;
    339 "M7ReportAmount" crate::ngap::M7ReportAmountMDT;
    340 "IncludeBeamMeasurementsIndication" crate::ngap::IncludeBeamMeasurementsIndication;
    341 "ExcessPacketDelayThresholdConfiguration" crate::ngap::ExcessPacketDelayThresholdConfiguration;
    342 "PagingCause" crate::ngap::PagingCause => PagingCause;
    343 "PagingCauseIndicationForVoiceService" crate::ngap::PagingCauseIndicationForVoiceService;
    344 "PEIPSassistanceInformation" crate::ngap::PEIPSassistanceInformation => PEIPSassistanceInformation;
    345 "FiveG-ProSeAuthorized" crate::ngap::FiveGProSeAuthorized => FiveG_ProSeAuthorized FiveGProSeAuthorized;
    346 "FiveG-ProSeUEPC5AggregateMaximumBitRate" crate::ngap::NRUESidelinkAggregateMaximumBitrate => FiveG_ProSeUEPC5AggregateMaximumBitRate;
    347 "FiveG-ProSePC5QoSParameters" crate::ngap::FiveGProSePC5QoSParameters => FiveG_ProSePC5QoSParameters FiveGProSePC5QoSParameters;
    348 "MBSSessionModificationFailureTransfer" rasn::types::OctetString, crate::ngap::MBSSessionSetupOrModFailureTransfer => MBSSessionModificationFailureTransfer;
    349 "MBSSessionModificationRequestTransfer" rasn::types::OctetString, crate::ngap::MBSSessionSetupOrModRequestTransfer => MBSSessionModificationRequestTransfer;
    350 "MBSSessionModificationResponseTransfer" rasn::types::OctetString, crate::ngap::MBSSessionSetupOrModResponseTransfer => MBSSessionModificationResponseTransfer;
    351 "MBS-QoSFlowToReleaseList" crate::ngap::QosFlowListWithCause => MBS_QoSFlowToReleaseList;
    352 "MBS-SessionTNLInfo5GC" crate::ngap::MBSSessionTNLInfo5GC => MBS_SessionTNLInfo5GC MBSSessionTNLInfo5GC;
    353 "TAINSAGSupportList" crate::ngap::TAINSAGSupportList;
    354 "SourceNodeTNLAddrInfo" crate::ngap::TransportLayerAddress;
    355 "NGAPIESupportInformationRequestList" crate::ngap::NGAPIESupportInformationRequestList;
    356 "NGAPIESupportInformationResponseList" crate::ngap::NGAPIESupportInformationResponseList;
    357 "MBS-SessionFSAIDList" crate::ngap::MBSSessionFSAIDList => MBS_SessionFSAIDList MBSSessionFSAIDList;
    358 "MBSSessionReleaseResponseTransfer" rasn::types::OctetString, crate::ngap::MBSSessionReleaseResponseTransfer => MBSSessionReleaseResponseTransfer;
    359 "ManagementBasedMDTPLMNModificationList" crate::ngap::MDTPLMNModificationList => ManagementBasedMDTPLMNModificationList MDTPLMNModificationList;
    360 "EarlyMeasurement" crate::ngap::EarlyMeasurement;
    361 "BeamMeasurementsReportConfiguration" crate::ngap::BeamMeasurementsReportConfiguration;
    362 "HFCNode-ID-new" crate::ngap::HFCNodeIDNew => HFCNode_ID_new HFCNodeIDNew;
    363 "GlobalCable-ID-new" crate::ngap::GlobalCableIDNew => GlobalCable_ID_new GlobalCableIDNew;
    364 "TargetHomeENB-ID" crate::ngap::TargetHomeENBID => TargetHomeENB_ID TargetHomeENBID;
    365 "HashedUEIdentityIndexValue" crate::ngap::HashedUEIdentityIndexValue;
    366 "ExtendedMobilityInformation" crate::ngap::ExtendedMobilityInformation;
    367 "NetworkControlledRepeaterAuthorized" crate::ngap::NetworkControlledRepeaterAuthorized => NetworkControlledRepeaterAuthorized;
    368 "AdditionalCancelledlocationReportingReferenceIDList" crate::ngap::AdditionalCancelledlocationReportingReferenceIDList;
    369 "Selected-Target-SNPN-Identity" crate::ngap::NID;
    370 "EquivalentSNPNsList" crate::ngap::EquivalentSNPNsList;
    371 "SelectedNID" crate::ngap::NID => SelectedNID;
    372 "SupportedUETypeList" crate::ngap::SupportedUETypeList => SupportedUETypeList;
    373 "AerialUEsubscriptionInformation" crate::ngap::AerialUEsubscriptionInformation => AerialUEsubscriptionInformation;
    374 "NR-A2X-ServicesAuthorized" crate::ngap::NRA2XServicesAuthorized => NR_A2X_ServicesAuthorized NRA2XServicesAuthorized;
    375 "LTE-A2X-ServicesAuthorized" crate::ngap::LTEA2XServicesAuthorized => LTE_A2X_ServicesAuthorized LTEA2XServicesAuthorized;
    376 "NR-A2X-UE-PC5-AggregateMaximumBitRate" crate::ngap::NRUESidelinkAggregateMaximumBitrate => NR_A2X_UE_PC5_AggregateMaximumBitRate;
    377 "LTE-A2X-UE-PC5-AggregateMaximumBitRate" crate::ngap::LTEUESidelinkAggregateMaximumBitrate => LTE_A2X_UE_PC5_AggregateMaximumBitRate;
    378 "A2X-PC5-QoS-Parameters" crate::ngap::A2XPC5QoSParameters => A2X_PC5_QoS_Parameters A2XPC5QoSParameters;
    379 "FiveGProSeLayer2Multipath" crate::ngap::FiveGProSeLayer2Multipath;
    380 "FiveGProSeLayer2UEtoUERelay" crate::ngap::FiveGProSeLayer2UEtoUERelay;
    381 "FiveGProSeLayer2UEtoUERemote" crate::ngap::FiveGProSeLayer2UEtoUERemote;
    382 "CandidateRelayUEInformationList" crate::ngap::CandidateRelayUEInformationList;
    383 "SuccessfulPSCellChangeReportList" crate::ngap::SuccessfulPSCellChangeReportList => SuccessfulPSCellChangeReportList;
    384 "IntersystemMobilityFailureforVoiceFallback" crate::ngap::IntersystemMobilityFailureforVoiceFallback => IntersystemMobilityFailureforVoiceFallback;
    385 "TargetCellCRNTI" crate::ngap::CRNTI;
    386 "TimeSinceFailure" crate::ngap::TimeSinceFailure;
    387 "RANTimingSynchronisationStatusInfo" crate::ngap::RANTimingSynchronisationStatusInfo => RANTimingSynchronisationStatusInfo;
    388 "RAN-TSSRequestType" crate::ngap::RANTSSRequestType => RAN_TSSRequestType RANTSSRequestType;
    389 "RAN-TSSScope" crate::ngap::RANTSSScope => RAN_TSSScope RANTSSScope;
    390 "ClockQualityReportingControlInfo" crate::ngap::ClockQualityReportingControlInfo;
    391 "RANfeedbacktype" crate::ngap::RANfeedbacktype;
    392 "QoSFlowTSCList" crate::ngap::QoSFlowTSCList;
    393 "TSCTrafficCharacteristicsFeedback" crate::ngap::TSCTrafficCharacteristicsFeedback;
    394 "DownlinkTLContainer" crate::ngap::TLContainer => DownlinkTLContainer TLContainer;
    395 "UplinkTLContainer" crate::ngap::TLContainer;
    396 "ANPacketDelayBudgetUL" crate::ngap::ExtendedPacketDelayBudget;
    397 "QosFlowAdditionalInfoList";
    398 "AssistanceInformationQoE-Meas" crate::ngap::AssistanceInformationQoEMeas;
    399 "CommServiceType" crate::ngap::CommServiceType;
    400 "MobileIAB-Authorized" crate::ngap::MobileIABAuthorized => MobileIAB_Authorized MobileIABAuthorized;
    401 "MobileIAB-MTUserLocationInformation" crate::ngap::MobileIABMTUserLocationInformation;
    402 "MobileIABNodeIndication" crate::ngap::MobileIABNodeIndication => MobileIABNodeIndication;
    403 "NoPDUSessionIndication" crate::ngap::NoPDUSessionIndication => NoPDUSessionIndication;
    404 "MobileIAB-Supported" crate::ngap::MobileIABSupported => MobileIAB_Supported MobileIABSupported;
    405 "CN-MT-CommunicationHandling" crate::ngap::CNMTCommunicationHandling;
    406 "FiveGCAction" crate::ngap::FiveGCAction => FiveGCAction;
    407 "PagingPolicyDifferentiation" crate::ngap::PagingPolicyDifferentiation => PagingPolicyDifferentiation;
    408 "DL-Signalling" crate::ngap::DLSignalling => DL_Signalling DLSignalling;
    409 "PNI-NPN-AreaScopeofMDT" crate::ngap::PNINPNAreaScopeofMDT;
    410 "PNI-NPNBasedMDT" crate::ngap::PNINPNBasedMDT => PNI_NPNBasedMDT PNINPNBasedMDT;
    411 "SNPN-CellBasedMDT" crate::ngap::SNPNCellBasedMDT => SNPN_CellBasedMDT SNPNCellBasedMDT;
    412 "SNPN-TAIBasedMDT" crate::ngap::SNPNTAIBasedMDT => SNPN_TAIBasedMDT SNPNTAIBasedMDT;
    413 "SNPN-BasedMDT" crate::ngap::SNPNBasedMDT => SNPN_BasedMDT SNPNBasedMDT;
    414 "Partially-Allowed-NSSAI" crate::ngap::PartiallyAllowedNSSAI => Partially_Allowed_NSSAI PartiallyAllowedNSSAI;
    415 "AssociatedSessionID" crate::ngap::AssociatedSessionID => AssociatedSessionID;
    416 "MBS-AssistanceInformation" crate::ngap::MBSAssistanceInformation;
    417 "BroadcastTransportFailureTransfer" rasn::types::OctetString, crate::ngap::BroadcastTransportFailureTransfer => BroadcastTransportFailureTransfer;
    418 "BroadcastTransportRequestTransfer" rasn::types::OctetString, crate::ngap::BroadcastTransportRequestTransfer => BroadcastTransportRequestTransfer;
    419 "BroadcastTransportResponseTransfer" rasn::types::OctetString, crate::ngap::BroadcastTransportResponseTransfer => BroadcastTransportResponseTransfer;
    420 "TimeBasedHandoverInformation" crate::ngap::TimeBasedHandoverInformation;
    421 "DLDiscarding" crate::ngap::DLDiscarding => DLDiscarding;
    422 "PDUsetQoSParameters" crate::ngap::PDUsetQoSParameters;
    423 "PDUSetbasedHandlingIndicator" crate::ngap::PDUSetbasedHandlingIndicator;
    424 "N6JitterInformation" crate::ngap::N6JitterInformation;
    425 "ECNMarkingorCongestionInformationReportingRequest" crate::ngap::ECNMarkingorCongestionInformationReportingRequest;
    426 "ECNMarkingorCongestionInformationReportingStatus" crate::ngap::ECNMarkingorCongestionInformationReportingStatus;
    427 "ERedCapIndication" crate::ngap::ERedCapIndication => ERedCapIndication;
    428 "XrDeviceWith2Rx" crate::ngap::XrDeviceWith2Rx => XrDeviceWith2Rx;
    429 "UserPlaneErrorIndicator" crate::ngap::UserPlaneErrorIndicator;
    430 "SLPositioningRangingServiceInfo" crate::ngap::SLPositioningRangingServiceInfo => SLPositioningRangingServiceInfo;
    431 "PDUSessionListMTCommHReq" crate::ngap::PDUSessionListMTCommHReq => PDUSessionListMTCommHReq;
    432 "MaximumDataBurstVolume" crate::ngap::MaximumDataBurstVolume;
    433 "MN-only-MDT-collection" crate::ngap::MNOnlyMDTCollection;
    434 "MBS-NGUFailureIndication" crate::ngap::MBSNGUFailureIndication => MBS_NGUFailureIndication MBSNGUFailureIndication;
    435 "UserPlaneFailureIndication" crate::ngap::UserPlaneFailureIndication => UserPlaneFailureIndication;
    436 "UserPlaneFailureIndicationReport" crate::ngap::UserPlaneFailureIndicationReport;
    437 "SourceSN-to-TargetSN-QMCInfo" crate::ngap::QMCConfigInfo;
    438 "QoERVQoEReportingPaths" crate::ngap::QoERVQoEReportingPaths;
    439 "UserLocationInformationN3IWF-without-PortNumber" crate::ngap::UserLocationInformationN3IWFWithoutPortNumber => UserLocationInformationN3IWF_without_PortNumber UserLocationInformationN3IWFWithoutPortNumber;
    440 "AUN3DeviceAccessInfo" crate::ngap::AUN3DeviceAccessInfo => AUN3DeviceAccessInfo;
    441 "TAIMBSSupportList" crate::ngap::TAIMBSSupportList;
    442 "ExtendedBackupAMFName" crate::ngap::ExtendedAMFName;
    443 "ExtendedOldAMF" crate::ngap::ExtendedAMFName => ExtendedOldAMF;
    444 "MBS-UP-FailureIndication" crate::ngap::MBSUPFailureIndication => MBS_UP_FailureIndication MBSUPFailureIndication;
    445 "RequestedTNLInfo" crate::ngap::RequestedTNLInfo;
    446 "Aerial-UE-FlightInformationOngoingReporting-failed" crate::ngap::AerialUEFlightInformationOngoingReportingFailed => Aerial_UE_FlightInformationOngoingReporting_failed AerialUEFlightInformationOngoingReportingFailed;
    447 "NetworkSliceAreaScopeofMDT" crate::ngap::NetworkSliceAreaScopeofMDT;
    448 "GeographyBasedMDT" crate::ngap::GeographyBasedMDT => GeographyBasedMDT;
    449 "MBS-IntendedServiceAreaList" crate::ngap::MBSIntendedServiceAreaList;
    450 "AMF-UE-NGAP-ID2" crate::ngap::AMFUENGAPID => AMF_UE_NGAP_ID2;
    451 "GUAMIList" crate::ngap::GUAMIList => GUAMIList;
    452 "GW-Context-Release-Indication" crate::ngap::GWContextReleaseIndication => GW_Context_Release_Indication GWContextReleaseIndication;
    453 "SourceAMF-GUAMI" crate::ngap::GUAMI => SourceAMF_GUAMI;
    454 "RequestedNSSAI" crate::ngap::RequestedNSSAI => RequestedNSSAI;
    455 "Target-RAN-Node-ID" crate::ngap::GlobalRANNodeID => Target_RAN_Node_ID;
    456 "InventoryRequestTransfer" rasn::types::OctetString, crate::ngap::InventoryRequestTransfer => InventoryRequestTransfer;
    457 "InventoryResponseTransfer" rasn::types::OctetString, crate::ngap::InventoryResponseTransfer => InventoryResponseTransfer;
    458 "InventoryFailureTransfer" rasn::types::OctetString, crate::ngap::InventoryFailureTransfer => InventoryFailureTransfer;
    459 "InventoryReportTransfer" rasn::types::OctetString, crate::ngap::InventoryReportTransfer => InventoryReportTransfer;
    460 "CommandRequestTransfer" rasn::types::OctetString, crate::ngap::CommandRequestTransfer => CommandRequestTransfer;
    461 "CommandResponseTransfer" rasn::types::OctetString, crate::ngap::CommandResponseTransfer => CommandResponseTransfer;
    462 "CommandFailureTransfer" rasn::types::OctetString, crate::ngap::CommandFailureTransfer => CommandFailureTransfer;
    463 "AIOTSessionReleaseCommandTransfer" rasn::types::OctetString, crate::ngap::AIOTSessionReleaseCommandTransfer => AIOTSessionReleaseCommandTransfer;
    464 "AIOTSessionReleaseCompleteTransfer" rasn::types::OctetString, crate::ngap::AIOTSessionReleaseCompleteTransfer => AIOTSessionReleaseCompleteTransfer;
    465 "AIOTSessionReleaseRequestTransfer" rasn::types::OctetString, crate::ngap::AIOTSessionReleaseRequestTransfer => AIOTSessionReleaseRequestTransfer;
    466 "AIoT-CorrelationIdentifier" crate::ngap::AIoTCorrelationIdentifier => AIoT_CorrelationIdentifier AIoTCorrelationIdentifier;
    467 "AIOTFIdentifier" crate::ngap::AIOTFIdentifier => AIOTFIdentifier;
    468 "AIoT-DeviceIdentificationRequested" crate::ngap::AIoTDeviceIdentificationRequested => AIoT_DeviceIdentificationRequested AIoTDeviceIdentificationRequested;
    469 "AIoT-RequestedServiceAreaInformation" crate::ngap::AIoTRequestedServiceAreaInformation => AIoT_RequestedServiceAreaInformation AIoTRequestedServiceAreaInformation;
    470 "AIoT-InventoryAssistanceInformation" crate::ngap::AIoTInventoryAssistanceInformation => AIoT_InventoryAssistanceInformation AIoTInventoryAssistanceInformation;
    471 "AIoT-FollowonCommandIndication" crate::ngap::AIoTFollowonCommandIndication => AIoT_FollowonCommandIndication AIoTFollowonCommandIndication;
    472 "RAN-AIOT-Device-NGAP-ID" crate::ngap::RANAIOTDeviceNGAPID => RAN_AIOT_Device_NGAP_ID RANAIOTDeviceNGAPID;
    473 "AIoT-CommandAssistanceInformation" crate::ngap::AIoTCommandAssistanceInformation => AIoT_CommandAssistanceInformation AIoTCommandAssistanceInformation;
    474 "AIoT-NASPDU" crate::ngap::AIoTNASPDU => AIoT_NASPDU AIoTNASPDU;
    475 "AIoT-Support" crate::ngap::AIoTSupport => AIoT_Support AIoTSupport;
    476 "AIOTFName" crate::ngap::AIOTFName => AIOTFName;
    477 "LPWUSPSAssistanceInformation" crate::ngap::LPWUSPSAssistanceInformation => LPWUSPSAssistanceInformation;
    478 "FurtherExtendedUEIdentityIndexValue" crate::ngap::FurtherExtendedUEIdentityIndexValue;
    479 "FiveGProSeLayer2MHUEtoNetworkRelay" crate::ngap::FiveGProSeLayer2MHUEtoNetworkRelay;
    480 "FiveGProSeLayer2MHIntermediateUEtoNetworkRelay" crate::ngap::FiveGProSeLayer2MHIntermediateUEtoNetworkRelay;
    481 "FiveGProSeLayer2MHRemote" crate::ngap::FiveGProSeLayer2MHRemote;
    482 "FiveGProSeLayer3MHUEtoNetworkRelay" crate::ngap::FiveGProSeLayer3MHUEtoNetworkRelay;
    483 "AdditionalULI" crate::ngap::AdditionalULI => AdditionalULI;
    484 "PduSetDelayBudgetDownlink" crate::ngap::ExtendedPacketDelayBudget;
    485 "PduSetDelayBudgetUplink" crate::ngap::ExtendedPacketDelayBudget;
    486 "PduSetErrorRateDownlink" crate::ngap::PacketErrorRate;
    487 "PduSetErrorRateUplink" crate::ngap::PacketErrorRate;
    488 "DLPDUSetInformationMarkingSupportIndication" crate::ngap::DLPDUSetInformationMarkingSupportIndication;
    489 "MonitoringRequestonAvailableBitrate" crate::ngap::MonitoringRequestonAvailableBitrate;
    490 "MMSID" crate::ngap::MMSID;
    491 "Indication-of-Bitrate-Adaptation" crate::ngap::IndicationOfBitrateAdaptation;
    492 "SCGActivationTime" crate::ngap::SCGActivationTime;
    493 "Aerial-UE-FlightInformationReporting" crate::ngap::AerialUEFlightInformationReporting;
    494 "Aerial-UE-FlightInformationReportingControlList" crate::ngap::AerialUEFlightInformationReportingControlList;
    495 "LPWUSDisableIndication" crate::ngap::LPWUSDisableIndication => LPWUSDisableIndication;
    496 "AIoT-SecurityInfo" crate::ngap::AIoTSecurityInfo => AIoT_SecurityInfo AIoTSecurityInfo;
}
